<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>RunLogin</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>d35b13c5-bcfa-4b59-a278-ae4e229198f4</testSuiteGuid>
   <testCaseLink>
      <guid>52ed0146-c4fa-4c5b-8755-b58702910eb3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login_TC</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>39a8c09d-f95d-401d-b65f-1db7b9f6e524</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/User</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>39a8c09d-f95d-401d-b65f-1db7b9f6e524</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>14c86d72-67eb-420e-a1d6-f8381890e4cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>39a8c09d-f95d-401d-b65f-1db7b9f6e524</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>c7e049a4-1887-4117-ab03-97a55e8b6c67</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
